package webhandle

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"mime"
	"net/http"
	"path/filepath"
	"strings"

	"github.com/drbawb/mustache"
	"github.com/xyproto/instapage"
	"github.com/xyproto/onthefly"
)

type (
	NewTemplateValueGenerator func(w http.ResponseWriter, req *http.Request) onthefly.TemplateValues
)

// type http.HandlerFunc er heller en struct som implementerer http.Handler interfacet (har en ServeHTTP func)

// Caching
var globalStringCache map[string]string

// Create a web.go compatible function that returns a string that is the HTML for this page
func NewGenerateHTML(page *onthefly.Page) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		w.Header().Add("Content-Type", "text/html")
		fmt.Fprint(w, page.GetXML(true))
	}
}

// Create a web.go compatible function that returns a string that is the HTML for this page
func NewGenerateHTMLwithTemplate(page *onthefly.Page, tvg NewTemplateValueGenerator) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		w.Header().Add("Content-Type", "text/html")
		values := tvg(w, req)
		fmt.Fprint(w, mustache.Render(page.GetXML(true), values))
	}
}

// Create a web.go compatible function that returns a string that is the CSS for this page
func NewGenerateCSS(page *onthefly.Page) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		w.Header().Add("Content-Type", "text/css")
		fmt.Fprint(w, page.GetCSS())
	}
}

// Create a web.go compatible function that returns a string that is the XML for this page
func NewGenerateXML(page *onthefly.Page) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		w.Header().Add("Content-Type", "text/xml")
		//w.Header().Add("Content-Type", "application/xml") // for human unreadable content
		fmt.Fprint(w, page.GetXML(false))
	}
}

// Creates a page based on the contents of "error.log". Useful for showing compile errors while creating an application.
func NewGenerateErrorHandler(errorfilename string) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		data, err := ioutil.ReadFile(errorfilename)
		if err != nil {
			fmt.Fprint(w, instapage.Message("Good", "No errors"))
			return
		}
		errors := strings.Replace(string(data), "\n", "</br>", -1)
		fmt.Fprint(w, instapage.Message("Errors", errors))
	}
}

// Takes a filename and returns a function that can handle the request
func NewFile(filename string) func(w http.ResponseWriter, req *http.Request) {
	var extension string
	if strings.Contains(filename, ".") {
		extension = filepath.Ext(filename)
	}
	return func(w http.ResponseWriter, req *http.Request) {
		if extension != "" {
			// TODO: Check if TypeByExtension returned something sensible
			w.Header().Add("Content-Type", mime.TypeByExtension(extension))
		}
		// TODO: Don't ignore errors
		filebytes, _ := ioutil.ReadFile(filename)
		buf := bytes.NewBuffer(filebytes)
		fmt.Fprint(w, buf.String())
	}
}

// Takes an url and a filename and offers that file at the given url
func NewPublishFile(mux *http.ServeMux, url, filename string) {
	mux.HandleFunc(url, NewFile(filename))
}

// Takes a filename and offers that file at the root url
func NewPublishRootFile(mux *http.ServeMux, filename string) {
	mux.HandleFunc("/"+filename, NewFile(filename))
}

// Expose the HTML and CSS generated by a page building function to the two given urls
func NewNewPublishPage(mux *http.ServeMux, htmlurl, cssurl string, buildfunction func(string) *onthefly.Page) {
	page := buildfunction(cssurl)
	mux.HandleFunc(htmlurl, NewGenerateHTML(page))
	mux.HandleFunc(cssurl, NewGenerateCSS(page))
}

func NewPublish(mux *http.ServeMux, url, filename string, cache bool) {
	if cache {
		mux.HandleFunc(url, NewCacheWrapper(url, NewFile(filename)))
	} else {
		mux.HandleFunc(url, NewFile(filename))
	}
}

// For a NotFound handler, look at net/http
